services:
  wordpress:
    image: wordpress:5.4.2-php7.2-apache
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ../../myvolume/wordpress:/var/www/html
    networks:
      - wp_network
    depends_on:
      - db
    deploy:
      replicas: 3

  db:
    image: mariadb:10.5
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ../../myvolume/mysql:/var/lib/mysql
    networks:
      - wp_network

  nginx:
    image: nginx:1.19.0
    container_name: nginx_load_balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress
    networks:
      - wp_network

networks:
  wp_network:
    driver: bridge
